//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViagemSeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class contas
    {
        public int Id { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Fornecedor { get; set; }
        public Nullable<int> Indentificador { get; set; }
        public Nullable<int> Viagem { get; set; }
        public Nullable<System.DateTime> DataRecebimento { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<int> Parcelas { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual cliente cliente1 { get; set; }
        public virtual fornecedor fornecedor1 { get; set; }
        public virtual viagem viagem1 { get; set; }
    }
}
