//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViagemSeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class fretamento
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal Km { get; set; }
        public decimal Valor { get; set; }
        public string Descricao { get; set; }
        public string Cliente { get; set; }
        public int Status { get; set; }
    }
}
