//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViagemSeg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancoviagemEntities : DbContext
    {
        public bancoviagemEntities()
            : base("name=bancoviagemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<contas> contas { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<fretamento> fretamento { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<hotelviagem> hotelviagem { get; set; }
        public virtual DbSet<pestacaoservico> pestacaoservico { get; set; }
        public virtual DbSet<veiculo> veiculo { get; set; }
        public virtual DbSet<vendacliente> vendacliente { get; set; }
        public virtual DbSet<viagem> viagem { get; set; }
    }
}
