//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViagemSeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class veiculo
    {
        public int Id { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Lugares { get; set; }
        public string Placa { get; set; }
        public string Identificacao { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
