//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViagemSeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaCliente
    {
        public int VendaId { get; set; }
        public Nullable<int> VendaIdCliente { get; set; }
        public Nullable<int> VendaIdViagem { get; set; }
        public Nullable<decimal> VendaValorViagem { get; set; }
        public Nullable<decimal> VendaValorPago { get; set; }
        public Nullable<decimal> VendaDesconto { get; set; }
        public string FaixaEtaria { get; set; }
        public Nullable<int> Status { get; set; }
        public int Assento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Viagem Viagem { get; set; }
    }
}
